// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface ISP1Verifier {
    function verifyProof(
        bytes32 programVKey,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view;
}

contract SovereignStateVerifier {
    // Contract State Anchors
    address public immutable sp1Verifier;
    bytes32 public immutable programVKey;
    bytes32 public currentEngineRoot;
    uint256 public lastSettledTimestamp;

    // Events
    event StateSettled(
        bytes32 indexed previousRoot,
        bytes32 indexed newRoot,
        double shearEnergy,
        uint256 timestamp
    );

    // Custom Errors
    error InvalidProof();
    error RootMismatch(bytes32 expected, bytes32 actual);

    struct PublicJournal {
        bytes32 previousRoot;
        bytes32 newRoot;
        uint64 shearEnergyBits; // IEEE 754 encoded double
        bool invariantValid;
    }

    constructor(address _sp1Verifier, bytes32 _programVKey, bytes32 _initialRoot) {
        sp1Verifier = _sp1Verifier;
        programVKey = _programVKey;
        currentEngineRoot = _initialRoot;
        lastSettledTimestamp = block.timestamp;
    }

    /**
     * @notice Verifies a ZK-STARK validity proof and updates the on-chain Sovereign Engine state root.
     * @param publicJournal ABI-encoded output values committed by the ZK-VM guest circuit.
     * @param proofBytes Succinct ZK proof generated by SP1 / RISC Zero.
     */
    function settleEngineState(
        bytes calldata publicJournal,
        bytes calldata proofBytes
    ) external {
        // 1. Decode public journal output committed by the ZK guest program
        PublicJournal memory journal = abi.decode(publicJournal, (PublicJournal));

        // 2. Enforce sequential root continuity
        if (journal.previousRoot != currentEngineRoot) {
            revert RootMismatch(currentEngineRoot, journal.previousRoot);
        }

        // 3. Verify ZK Proof against canonical SP1 Verifier
        try ISP1Verifier(sp1Verifier).verifyProof(programVKey, publicJournal, proofBytes) {
            // Proof is valid
        } catch {
            revert InvalidProof();
        }

        // 4. Update state root and timestamp
        currentEngineRoot = journal.newRoot;
        lastSettledTimestamp = block.timestamp;

        emit StateSettled(
            journal.previousRoot,
            journal.newRoot,
            journal.shearEnergyBits,
            block.timestamp
        );
    }
}
